# Generated by Django 5.2.7 on 2025-10-21 21:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default', max_length=255, null=True, verbose_name='image'),
        ),
    ]
