# Generated by Django 5.2.7 on 2025-12-19 13:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0003_alter_project_image_alter_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('certificate_name', models.CharField(max_length=200)),
                ('certificate_id', models.CharField(blank=True, max_length=200, null=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verify_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, default='default', max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
